### ISSUE TITLE
Problemas de instalación

### ISSUE THREAD

**Issue by RorroPoblete** [IIC2143/Syllabus#2]
Buenas tardes,

tengo problemas con la instalación de ruby, ya que en mi pc (macOs) viene instalado por defecto ruby 2.6.10p210 y no me deja actualizarlo. Cuando corro rvm install 3.1.0, me deja el siguiente error:
Error running '__rvm_make -j8',
please read /Users/rodrigopoblete/.rvm/log/1678288747_ruby-3.1.0/make.log

There has been an error while running make. Halting the installation.

Gracias.

**Comment by RorroPoblete** [comment]
Ya lo solucioné.

**Comment by cata-p** [comment]
Tengo el mismo error, cómo lo solucionaste?

**Comment by RorroPoblete** [comment]
No estaba ocupando el terminal rosetta, al cambiarlo me funcionó

**Comment by dvaldesg** [comment]
Hola, resintalé todo incluso con alguien que ya dió el ramo en el curso y no hemos logrado solucionar este error.
"
We could not find your database: postgres. Which can be found in the database configuration file located at config/database.yml.

To resolve this issue:

- Did you create the database for this app, or delete it? You may need to create your database.
- Has the database name changed? Check your database.yml config has the correct database name.

To create your database, run:

        bin/rails db:create
Couldn't create 'MyApp_development' database. Please check your configuration.
rails aborted!
ActiveRecord::NoDatabaseError: We could not find your database: postgres. Which can be found in the database configuration file located at config/database.yml.

To resolve this issue:

- Did you create the database for this app, or delete it? You may need to create your database.
- Has the database name changed? Check your database.yml config has the correct database name.

To create your database, run:

        bin/rails db:create


Caused by:
PG::ConnectionBad: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "root" does not exist

Tasks: TOP => db:create
(See full trace by running task with --trace)
"
Alguien sabe como solucionarlo?

**Comment by nicoolivaresm** [comment]
Hola, todavía no logro hacer el setup, estoy teniendo problemas con la instalación de Postgresql. Todavía no puedo empezar la tarea por este problema. 

<img width="564" alt="Captura de pantalla 2023-03-18 a la(s) 16 03 34" src="https://user-images.githubusercontent.com/106032490/226130877-6a1e74eb-85c8-44b1-895e-8da256b14e48.png">
